### ISSUE TITLE
Scripts being called twice

### ISSUE THREAD

**Issue by danielfariati** [eduardolundgren/senna#84]
Sometimes, the scripts in the new page is being called twice.

Example:
``index.html``
```html
<div>
    <span>Menu:</span>
    <span><a href="/">Home</a></span>
    <span><a href="/other-page">Other page</a></span>
</div>
<div id="content">
    <div id="content-default">
        Main Page!
    </div>
</div>
```

---

``other-page.html``
```html
<div>
    <span>Menu:</span>
    <span><a href="/">Home</a></span>
    <span><a href="/other-page">Other page</a></span>
</div>
<div id="content">
    <div id="content-default">
        Other page
        <script type="text/javascript">console.log("test!");</script>
    </div>
</div>
```

---

``application.js``
```javascript
var app = new senna.App();
app.addSurfaces('content');
app.addRoutes(new senna.Route(/.*/, senna.HtmlScreen);
```

The console will show the "*test!*" message twice when the *other-page.html* is called.

---

It appears to be a problem with the lines 1709 and 1804 of senna.js. That happens because both lines call the method *append*, which call the method *parseScripts*.

A solution would be to change those lines to parse the scripts only once.

**Comment by eduardolundgren** [comment]
Fixed. Thanks!
