### ISSUE TITLE
Dynamic body id or class

### ISSUE THREAD

**Issue by letunglam** [eduardolundgren/senna#86]
I'm a newbie to javascript, so please forgive if I ask things that are painfully obvious. 

I am using Senna to in my side project. I can update any section dynamically with Senna. But when I want Senna update body class or id dynamically too, I don't know how to do it. I tried to search Senna's documentation and around github but I couldn't find a solution. Could somebody please help. 

Many thanks in advance

**Comment by eduardolundgren** [comment]
Surfaces must be child of document.body, then if you try to use body as surface it won't work. If you want to change body during a surface navigation you can use the custom events to manually add the behavior.

**Comment by letunglam** [comment]
@eduardolundgren Thank you. So I think Route Handler would be better solution for my issue.

**Comment by eduardolundgren** [comment]
SGTM.
