### ISSUE TITLE
How to add screen deactivate transition?

### ISSUE THREAD

**Issue by letunglam** [eduardolundgren/senna#87]
I'm a newbie to javascript, so please forgive if I ask things that are painfully obvious.

I can set transition when a screen appear by using `surface.setTransitionFn` but I don't know how can I set transition when it disappear (ex: fadeOut). A simple example would be highly appreciated.

**Comment by eduardolundgren** [comment]
Note that the default transition adds a class flipped to the surface that is visible, and removes it from the ones it will hide, se https://github.com/eduardolundgren/senna/blob/master/src/surface/Surface.js#L62. Therefore, you can use css transitions to handle that, see https://github.com/eduardolundgren/senna/blob/master/src/senna.css#L41.

**Comment by letunglam** [comment]
@eduardolundgren thank you for your quick reply

However, as I see from the Gallery example, class `.flipped` stay in preview surface even if it's hided. Is it a bug?

**Comment by eduardolundgren** [comment]
If it's hidden the flipped will not affect anything, although it seems something that can be fixed. Feel free to send a pull or open an issue for that.

**Comment by letunglam** [comment]
@eduardolundgren Thank you for the information. As I am just a javascript newbie, I will try my best ^^.
