### ISSUE TITLE
Prevent click a link from jumping to top of page in jQuery

### ISSUE THREAD

**Issue by letunglam** [eduardolundgren/senna#88]
I have a issue like in gallery example. When click a click, it makes the page jump to the top. I used to use this code to fix it. However it also prevents senna from working.

```
$('a').click(function(e) {
     // do something 
     return false;
     e.preventDefault();
});
```

Any help would be very appreciated.

**Comment by eduardolundgren** [comment]
You can manually invoke `app.navigate(href)` to work around this issue.

**Comment by letunglam** [comment]
@eduardolundgren Thank you for your kind support. I fixed it :D

**Comment by eduardolundgren** [comment]
:+1:
