### ISSUE TITLE
Using .on('startNavigate' doesn't allow me to update the event.path before the request is sent.

### ISSUE THREAD

**Issue by bryceosterhaus** [eduardolundgren/senna#96]
I am trying to update the path to include a parameter on each senna request using

```javascript
app.on('startNavigate', function(event) {
	event.path += '&p_p_isolate=1';
});
```

However, the event.path is only updated AFTER the request is sent. It is expected that 'startNavigate' would occur right before the request is sent and thus allowing the developer to update the path before the request is sent.

Thanks!

**Comment by eduardolundgren** [comment]
One option is to add a resolvePath attribute on App, that by default is a identity function. If set to a different one you can place your custom logic there. Would you mind sending a pull request with that?

**Comment by bryceosterhaus** [comment]
Updated pr to include test
